lime.lo: /home/zephir/limepie/ext/test/php-5.5.8/ext/lime/lime.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zephir/limepie/ext/test/php-5.5.8/ext/lime $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zephir/limepie/ext/test/php-5.5.8/ext/lime/lime.c -o lime.lo 
$(phplibdir)/lime.la: ./lime.la
	$(LIBTOOL) --mode=install cp ./lime.la $(phplibdir)

./lime.la: $(shared_objects_lime) $(LIME_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_lime) $(LIME_SHARED_LIBADD)

